apiVersion: v1
kind: Service
metadata:
  name: s3-failure-flags-app
spec:
  selector:
    app: s3-failure-flags-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

